![](./radar_eval/gui/resources/pics/Logo_Sykno.svg "")

# __Radar Data Evaluation__ - ___Jupyter Notebook___

---
### __Introduction__

**Radar Data Measurement:**

- Radar Measurements Path (HDF5 Files): `/project_root/radar_eval/measurement/hdf5/`
- Radar HDF5 Controller for interaction via Radar Eval GUI or within the Jupyter Notebook: `/project_root/radar_eval/measurement/hdf5_controller.py` (see Radar HDF5 Controller Usage)
- The Radar radar data is a Numpy array `radar_data_cube` with a shape of `(n_frames, n_samples_per_chirp, n_rx, n_tx, n_shape_sets)` and its `dtype` is `float32`.


**Radar HDF5 Structure:**
- __/__
  - __Data__
    - ***Frame_Data_Cube_XXXX_ZZZZ***
      - `@delta_time`: `np.float32`
      - `@shape`: `(n_samples_per_chirp, n_rx, n_tx, n_shapes)`
      - `@timestamp`: `np.float32`
      - ...
  - __Metadata__
    - ***radar_bgt_reg_content***
      - `@radar_bgt_reg_content`:
    - ***radar_bgt_reg_content_readable***
      - `@radar_bgt_reg_content_readable`:
    - ***radar_config***
      - `@radar_config`:
    - ***radar_radar_parameters*** 
      - `radar_radar_parameters`

***Frame_Data_Cube_XXXX_ZZZZ*** where ***XXXX*** are multiples of `4095` and ***ZZZZ*** is the frame counter with values in the range $[0, 4095]$.

- ***XXXX*** $\in \{k \cdot 4095 \mid k \in \mathbb{N}, 0 \leq k \leq 9999\}$
- ***ZZZZ*** $\in \{0, 1, 2, \ldots, 4095\}$


**Radar data cube structure:**
| Dimension            | Size |
|----------------------|------|
| Number of samples    | n_samples_per_chirp $\in \{2^n \mid n \in \mathbb{N}, 6 \leq n \leq 11\}$ |
| Number of RX antennas| n_rx_active_antennas $\in \{n \mid n \in \mathbb{N}, 1 \leq n \leq 4\}$ |
| Number of TX antennas| n_tx_active_antennas $\in \{n \mid n \in \mathbb{N}, 1 \leq n \leq 2\}$ |
| Number of shape sets | n_shapes $\in \{n \mid n \in \mathbb{N}, 1 \leq n \leq 4095\}$ |
| Number of frames     | n_frames $\in \{n \mid n \in \mathbb{N}, 0 \leq n \leq 4095\}$ |


**Chirp data structure:**

| Samples      | ADC Channel 1 (RX1) |ADC Channel 2 (RX2) |ADC Channel 3 (RX3) |ADC Channel 4 (RX4) |
|-----------------|------------------------------|-----------------|------------------------------|-----------------|
| 0         | dtype=np.uint16 | dtype=np.uint16 | dtype=np.uint16 | dtype=np.uint16 |
| 1         | 12 bit ADC | 12 bit ADC | 12 bit ADC | 12 bit ADC |
| 2         | 0 - 1.2 V | 0 - 1.2 V | 0 - 1.2 V | 0 - 1.2 V |
| ...             | ...                          | ...                          | ...                          | ...                          |
| n-1         | 0 - 4095 | 0 - 4095 | 0 - 4095 | 0 - 4095 |


**Working with HDF5:**

- List measurement structure:
```sh 
    h5ls -r radar_hdf5_filename.hdf5
```
- Inspect a specific group or dataset:
```sh
    h5dump -d /Data/Frame_Data_Cube_XXXX_ZZZZ radar_hdf5_filename.hdf5
```
- Inspect measurement meta data:
```sh
    h5dump -g /Metadata radar_hdf5_filename.hdf5
```
- Get statistics e.g. number of groups, datasets, and attributes:
```sh
    h5stat radar_hdf5_filename.hdf5
```


In [1]:
description = "Radar Root is: "
radar_root = !pwd
print(f"{description}{radar_root[0]}")
radar_meas_hdf5_path = f'{radar_root[0]}/radar_eval/measurement/hdf5/'
!tree -C {radar_meas_hdf5_path}

Radar Root is: /home/jurnijasted/coding/sykno/MiRa_IFX_60GHz_2x4/sykno_radar_gui/sykno_radar_eval_project
/home/jurnijasted/coding/sykno/MiRa_IFX_60GHz_2x4/sykno_radar_gui/sykno_radar_eval_project/radar_eval/measurement/hdf5/
└── MiRa6024I1A_Measurement_01_06_2024_00_00_00.hdf5

0 directories, 1 file


In [2]:
radar_meas_hdf5_file_path = f'{radar_meas_hdf5_path}/MiRa6024I1A_Measurement_01_06_2024_00_00_00_Session.hdf5'

In [3]:
!h5ls -r {radar_meas_hdf5_file_path}

/home/jurnijasted/coding/sykno/MiRa_IFX_60GHz_2x4/sykno_radar_gui/sykno_radar_eval_project/radar_eval/measurement/hdf5//MiRa6024I1A_Measurement_01_06_2024_00_00_00_Session.hdf5: unable to open file


In [4]:
!h5dump -d /Data/Frame_Data_Cube_0000_0001 {radar_meas_hdf5_file_path}

h5dump error: unable to open file "/home/jurnijasted/coding/sykno/MiRa_IFX_60GHz_2x4/sykno_radar_gui/sykno_radar_eval_project/radar_eval/measurement/hdf5//MiRa6024I1A_Measurement_01_06_2024_00_00_00_Session.hdf5"


In [5]:
!h5dump -g /Metadata {radar_meas_hdf5_file_path}

h5dump error: unable to open file "/home/jurnijasted/coding/sykno/MiRa_IFX_60GHz_2x4/sykno_radar_gui/sykno_radar_eval_project/radar_eval/measurement/hdf5//MiRa6024I1A_Measurement_01_06_2024_00_00_00_Session.hdf5"


In [6]:
!h5stat {radar_meas_hdf5_file_path}

Filename: /home/jurnijasted/coding/sykno/MiRa_IFX_60GHz_2x4/sykno_radar_gui/sykno_radar_eval_project/radar_eval/measurement/hdf5//MiRa6024I1A_Measurement_01_06_2024_00_00_00_Session.hdf5
h5stat error: unable to open file "/home/jurnijasted/coding/sykno/MiRa_IFX_60GHz_2x4/sykno_radar_gui/sykno_radar_eval_project/radar_eval/measurement/hdf5//MiRa6024I1A_Measurement_01_06_2024_00_00_00_Session.hdf5"


___
### __Radar Data Evaluation__ - ___Python Code___


#### ***Radar HDF5 Controller Usage***


In [7]:
import os
import numpy as np
import ipywidgets as widgets
from radar_eval.measurement.hdf5_controller import MIRA_HDF5_CTRL
from radar_eval.radar_system.radar_system_definition import MIRA_RADAR_PARAMETER
radar_meas_hdf5_path = './radar_eval/measurement/hdf5/'

# List all files in the folder
file_names = os.listdir(radar_meas_hdf5_path)

# Filter out non-file entries if needed
file_names = [f for f in file_names if os.path.isfile(os.path.join(radar_meas_hdf5_path, f)) and f != '.gitkeep']
sorted_file_names = sorted(file_names)

# Dropdown for file selection
file_dropdown = widgets.Dropdown(
    options=file_names,
    description=f'Select a File:',
)
print((f'Radar HDF5 Files in {radar_meas_hdf5_path}:'))
file_dropdown.layout.width = '650px'  # Adjust the width as needed
display(file_dropdown)



Radar HDF5 Files in ./radar_eval/measurement/hdf5/:


Dropdown(description='Select a File:', layout=Layout(width='650px'), options=('MiRa6024I1A_Measurement_01_06_2…

In [8]:
from pathlib import Path
radar_hdf5_controller = MIRA_HDF5_CTRL(Path(radar_meas_hdf5_path+str(file_dropdown.value)).resolve())
data = radar_hdf5_controller.read_dataset("/Data/Frame_Data_Cube_0000_0000")
print(data)

[[[[2046. 2045. 2046. ... 2046. 2046. 2045.]
   [2081. 2082. 2080. ... 2081. 2082. 2078.]]

  [[1996. 1994. 1996. ... 1995. 1994. 1994.]
   [2152. 2150. 2150. ... 2150. 2148. 2148.]]

  [[2006. 2004. 2006. ... 2004. 2006. 2006.]
   [2056. 2054. 2054. ... 2056. 2054. 2056.]]

  [[1998. 1998. 2000. ... 2000. 2000. 2000.]
   [1954. 1952. 1950. ... 1952. 1952. 1952.]]]


 [[[2048. 2048. 2048. ... 2050. 2049. 2048.]
   [2056. 2055. 2056. ... 2056. 2055. 2056.]]

  [[2026. 2026. 2026. ... 2029. 2026. 2028.]
   [2062. 2064. 2066. ... 2064. 2064. 2064.]]

  [[2044. 2046. 2045. ... 2046. 2046. 2046.]
   [2058. 2058. 2057. ... 2058. 2057. 2058.]]

  [[2036. 2037. 2036. ... 2036. 2037. 2038.]
   [2014. 2014. 2014. ... 2014. 2014. 2013.]]]


 [[[2045. 2046. 2044. ... 2044. 2044. 2044.]
   [2036. 2036. 2038. ... 2038. 2038. 2039.]]

  [[2046. 2046. 2046. ... 2046. 2046. 2046.]
   [2020. 2018. 2020. ... 2022. 2020. 2021.]]

  [[2052. 2054. 2054. ... 2054. 2054. 2054.]
   [2046. 2046. 2046. ... 2046.

In [9]:
radar_hdf5_controller.print_hdf5_structure()

- /
  - Data
    - Frame_Data_Cube_0000_0000 (Dataset)
      - @delta_time: 0.9393777847290039
      - @shape: (512, 4, 2, 128)
      - @timestamp: 1717398634.5613716
    - Frame_Data_Cube_0000_0001 (Dataset)
      - @delta_time: 0.0435795783996582
      - @shape: (512, 4, 2, 128)
      - @timestamp: 1717398634.6049511
    - Frame_Data_Cube_0000_0002 (Dataset)
      - @delta_time: 0.049294233322143555
      - @shape: (512, 4, 2, 128)
      - @timestamp: 1717398634.6542454
  - Metadata
    - mira_bgt_reg_content
      - @mira_bgt_reg_content: reg 0x00 0x1c4f70
reg 0x01 0x070210
reg 0x02 0x000504
reg 0x03 0x000000
reg 0x04 0xe967fd
reg 0x05 0x0805b4
reg 0x06 0x152fff
reg 0x07 0x0109c0
reg 0x08 0x000050
reg 0x0c 0x000050
reg 0x10 0x1ffc51
reg 0x13 0x000000
reg 0x17 0x1ffc54
reg 0x1a 0x000000
reg 0x1e 0x000000
reg 0x21 0x000000
reg 0x25 0x000000
reg 0x28 0x000000
reg 0x09 0x000000
reg 0x0d 0x000000
reg 0x11 0xff17ff
reg 0x14 0x0003ff
reg 0x18 0xff17ff
reg 0x1b 0x0003ff
reg 0x1f 0x0003ff
re

In [10]:
stats = radar_hdf5_controller.get_dataset_statistics("/Data/Frame_Data_Cube_0000_0001")
print(stats)

{'mean': 1989.42, 'std_dev': 197.84596, 'min': 1034.0, 'max': 2414.0}


In [11]:
info = radar_hdf5_controller.get_dataset_info("/Data/Frame_Data_Cube_0000_0001")
print(info)

((512, 4, 2, 128), dtype('<f4'))


In [12]:
frame_data_cube = radar_hdf5_controller.get_dataset_slice("/Data/Frame_Data_Cube_0000_0001")

In [13]:
metadata = radar_hdf5_controller.read_metadata()
print(metadata)

{'mira_bgt_reg_content': {'mira_bgt_reg_content': 'reg 0x00 0x1c4f70\nreg 0x01 0x070210\nreg 0x02 0x000504\nreg 0x03 0x000000\nreg 0x04 0xe967fd\nreg 0x05 0x0805b4\nreg 0x06 0x152fff\nreg 0x07 0x0109c0\nreg 0x08 0x000050\nreg 0x0c 0x000050\nreg 0x10 0x1ffc51\nreg 0x13 0x000000\nreg 0x17 0x1ffc54\nreg 0x1a 0x000000\nreg 0x1e 0x000000\nreg 0x21 0x000000\nreg 0x25 0x000000\nreg 0x28 0x000000\nreg 0x09 0x000000\nreg 0x0d 0x000000\nreg 0x11 0xff17ff\nreg 0x14 0x0003ff\nreg 0x18 0xff17ff\nreg 0x1b 0x0003ff\nreg 0x1f 0x0003ff\nreg 0x22 0x0003ff\nreg 0x26 0x0003ff\nreg 0x29 0x0003ff\nreg 0x0a 0x000000\nreg 0x0e 0x000000\nreg 0x12 0x800000\nreg 0x15 0x800000\nreg 0x19 0x800000\nreg 0x1c 0x800000\nreg 0x20 0x800000\nreg 0x23 0x800000\nreg 0x27 0x800000\nreg 0x2a 0x800000\nreg 0x0b 0x000080\nreg 0x0f 0x000080\nreg 0x16 0x000090\nreg 0x1d 0x000090\nreg 0x24 0x000080\nreg 0x2b 0x000080\nreg 0x2c 0x367e8e\nreg 0x2d 0x24fc49\nreg 0x2e 0x0ff000\nreg 0x2f 0x985a9d\nreg 0x30 0xa4409a\nreg 0x38 0xa4409a\

In [14]:
radar_param: MIRA_RADAR_PARAMETER = radar_hdf5_controller.unpickle_metadata()
print(radar_param)

In [15]:
radar_data_cube = np.array(radar_hdf5_controller.load_radar_data_cube(), dtype=np.float32)
print(radar_data_cube.shape, radar_data_cube.dtype)

(3, 512, 4, 2, 128) float32


---
#### ***Inspect Radar Dataset***

1. **Load python packages and Radar HDF5 measurement file**


2. **Open Radar HDF5 measurement file, load meta data and build radar data cube**

3. **Radar HDF5 measurement - data profiling**

    __Inspect Radar Radar System Parameters__
    - __radar_param__: meta-class contains __All__ other sub-classes
        - __sys__: sub-class contains __Radar__ specific values
        - __dsp__: sub-class contains __DSP__ parameters
        - __mon__: sub-class to __Monitor__ frame count, duration time, etc.
        - __gui__: sub-class contains __GUI__ relevant parameters
        - __meas__: sub-class contains __Measurement__ relevant parameters
        - __remt__: sub-class contains __Remote Control__ relevant parameters
        - __rply__: sub-class contains __Replay Control__ relevant parameters 

In [16]:
print(f"{radar_param.__dict__=}")
print(f"{radar_param.dsp.__dict__=}")
print(f"{radar_param.gui.__dict__=}")
print(f"{radar_param.mon.__dict__=}")
print(f"{radar_param.sys.__dict__=}")
print(f"{radar_param.meas.__dict__=}")
print(f"{radar_param.remt.__dict__=}")
print(f"{radar_param.rply.__dict__=}")

radar_param.__dict__={'gui': <radar_eval.radar_system.radar_system_definition.MIRA_RADAR_GUI_PARAMETER object at 0x7d4cdf5d0460>, 'dsp': <radar_eval.radar_system.radar_system_definition.MIRA_RADAR_DSP_PARAMETER object at 0x7d4cdf5d0130>, 'sens': <radar_eval.radar_system.radar_system_definition.MIRA_RADAR_SENS_PARAMETER object at 0x7d4cdf5d11b0>, 'sys': <radar_eval.radar_system.radar_system_definition.MIRA_RADAR_SYS_PARAMETER object at 0x7d4cdf5b2a70>, 'mon': <radar_eval.radar_system.radar_system_definition.MIRA_RADAR_MON_PARAMETER object at 0x7d4c75206080>, 'meas': <radar_eval.radar_system.radar_system_definition.MIRA_RADAR_MEAS_PARAMETER object at 0x7d4c752061d0>, 'rply': <radar_eval.radar_system.radar_system_definition.MIRA_RADAR_RPLY_PARAMETER object at 0x7d4c75206200>, 'remt': <radar_eval.radar_system.radar_system_definition.MIRA_RADAR_REMT_PARAMETER object at 0x7d4c75206260>}
radar_param.dsp.__dict__={'axis_max_value': 0, 'padding_len': 0, 'window_func': 'hanning', 'axis_unit': ''

3. **Radar HDF5 measurement - data profiling**

    1. __Check Radar System Parameters__
    - __radar_param__: meta-class contains __All__ other sub-classes

In [17]:
print(f"{radar_data_cube.shape=}")
print(f"{frame_data_cube.shape=}\n" + \
      f"{radar_hdf5_controller.delta_time=}\n" + \
      f"{radar_hdf5_controller.shape=}\n" + \
      f"{radar_hdf5_controller.timestamp=}")

print(f"{frame_data_cube[:1,:,:,0]}")


radar_data_cube.shape=(3, 512, 4, 2, 128)
frame_data_cube.shape=(512, 4, 2, 128)
radar_hdf5_controller.delta_time=None
radar_hdf5_controller.shape=None
radar_hdf5_controller.timestamp=None
[[[2044. 2078.]
  [2000. 2150.]
  [2006. 2056.]
  [2000. 1952.]]]
