![](./radar_eval/gui/resources/pics/Logo_Sykno.svg "")

# __Radar Data Evaluation__ - ___Jupyter Notebook___

---
### __Introduction__

**Radar Data Measurement:**

- Radar Measurements Path (HDF5 Files): `/project_root/radar_eval/measurement/hdf5/`
- Radar HDF5 Controller for interaction via Radar Eval GUI or within the Jupyter Notebook: `/project_root/radar_eval/measurement/hdf5_controller.py` (see Radar HDF5 Controller Usage)
- The Radar radar data is a Numpy array `radar_data_cube` with a shape of `(n_frames, n_samples_per_chirp, n_rx, n_tx, n_shape_sets)` and its `dtype` is `float32`.


**Radar HDF5 Structure:**
- __/__
  - __Data__
    - ***Frame_Data_Cube_XXXX_ZZZZ***
      - `@delta_time`: `np.float32`
      - `@shape`: `(n_samples_per_chirp, n_rx, n_tx, n_shapes)`
      - `@timestamp`: `np.float32`
      - ...
  - __Metadata__
    - ***radar_bgt_reg_content***
      - `@radar_bgt_reg_content`:
    - ***radar_bgt_reg_content_readable***
      - `@radar_bgt_reg_content_readable`:
    - ***radar_config***
      - `@radar_config`:
    - ***radar_radar_parameters*** 
      - `radar_radar_parameters`

***Frame_Data_Cube_XXXX_ZZZZ*** where ***XXXX*** are multiples of `4095` and ***ZZZZ*** is the frame counter with values in the range $[0, 4095]$.

- ***XXXX*** $\in \{k \cdot 4095 \mid k \in \mathbb{N}, 0 \leq k \leq 9999\}$
- ***ZZZZ*** $\in \{0, 1, 2, \ldots, 4095\}$


**Radar data cube structure:**
| Dimension            | Size |
|----------------------|------|
| Number of samples    | n_samples_per_chirp $\in \{2^n \mid n \in \mathbb{N}, 6 \leq n \leq 11\}$ |
| Number of RX antennas| n_rx_active_antennas $\in \{n \mid n \in \mathbb{N}, 1 \leq n \leq 4\}$ |
| Number of TX antennas| n_tx_active_antennas $\in \{n \mid n \in \mathbb{N}, 1 \leq n \leq 2\}$ |
| Number of shape sets | n_shapes $\in \{n \mid n \in \mathbb{N}, 1 \leq n \leq 4095\}$ |
| Number of frames     | n_frames $\in \{n \mid n \in \mathbb{N}, 0 \leq n \leq 4095\}$ |


**Chirp data structure:**

| Samples      | ADC Channel 1 (RX1) |ADC Channel 2 (RX2) |ADC Channel 3 (RX3) |ADC Channel 4 (RX4) |
|-----------------|------------------------------|-----------------|------------------------------|-----------------|
| 0         | dtype=np.uint16 | dtype=np.uint16 | dtype=np.uint16 | dtype=np.uint16 |
| 1         | 12 bit ADC | 12 bit ADC | 12 bit ADC | 12 bit ADC |
| 2         | 0 - 1.2 V | 0 - 1.2 V | 0 - 1.2 V | 0 - 1.2 V |
| ...             | ...                          | ...                          | ...                          | ...                          |
| n-1         | 0 - 4095 | 0 - 4095 | 0 - 4095 | 0 - 4095 |


**Working with HDF5:**

- List measurement structure:
```sh 
    h5ls -r radar_hdf5_filename.hdf5
```
- Inspect a specific group or dataset:
```sh
    h5dump -d /Data/Frame_Data_Cube_XXXX_ZZZZ radar_hdf5_filename.hdf5
```
- Inspect measurement meta data:
```sh
    h5dump -g /Metadata radar_hdf5_filename.hdf5
```
- Get statistics e.g. number of groups, datasets, and attributes:
```sh
    h5stat radar_hdf5_filename.hdf5
```


In [35]:
description = "Radar Root is: "
radar_root = !pwd
print(f"{description}{radar_root[0]}")
radar_meas_hdf5_path = f'{radar_root[0]}/radar_eval/measurement/hdf5/'
!tree -C {radar_meas_hdf5_path}

Radar Root is: /home/jurnijasted/coding/sykno/MiRa_IFX_60GHz_2x4/sykno_radar_gui/sykno_radar_eval_project
/home/jurnijasted/coding/sykno/MiRa_IFX_60GHz_2x4/sykno_radar_gui/sykno_radar_eval_project/radar_eval/measurement/hdf5/
└── SY60I11_Measurement_26_08_2024_13_55_44_Default_Session.hdf5

0 directories, 1 file


In [36]:
radar_meas_hdf5_file_path = f'{radar_meas_hdf5_path}/SY60I11_Measurement_26_08_2024_13_55_44_Default_Session.hdf5'

In [37]:
!h5ls -r {radar_meas_hdf5_file_path}

/                        Group
/Data                    Group
/Data/Frame_Data_Cube_0000_0000 Dataset {256, 1, 1, 64}
/Data/Frame_Data_Cube_0000_0001 Dataset {256, 1, 1, 64}
/Data/Frame_Data_Cube_0000_0002 Dataset {256, 1, 1, 64}
/Data/Frame_Data_Cube_0000_0003 Dataset {256, 1, 1, 64}
/Data/Frame_Data_Cube_0000_0004 Dataset {256, 1, 1, 64}
/Data/Frame_Data_Cube_0000_0005 Dataset {256, 1, 1, 64}
/Data/Frame_Data_Cube_0000_0006 Dataset {256, 1, 1, 64}
/Data/Frame_Data_Cube_0000_0007 Dataset {256, 1, 1, 64}
/Data/Frame_Data_Cube_0000_0008 Dataset {256, 1, 1, 64}
/Data/Frame_Data_Cube_0000_0009 Dataset {256, 1, 1, 64}
/Data/Frame_Data_Cube_0000_0010 Dataset {256, 1, 1, 64}
/Data/Frame_Data_Cube_0000_0011 Dataset {256, 1, 1, 64}
/Data/Frame_Data_Cube_0000_0012 Dataset {256, 1, 1, 64}
/Data/Frame_Data_Cube_0000_0013 Dataset {256, 1, 1, 64}
/Data/Frame_Data_Cube_0000_0014 Dataset {256, 1, 1, 64}
/Data/Frame_Data_Cube_0000_0015 Dataset {256, 1, 1, 64}
/Data/Frame_Data_Cube_0000_0016 Dataset {2

In [38]:
!h5dump -d /Data/Frame_Data_Cube_0000_0000 {radar_meas_hdf5_file_path}

HDF5 "/home/jurnijasted/coding/sykno/MiRa_IFX_60GHz_2x4/sykno_radar_gui/sykno_radar_eval_project/radar_eval/measurement/hdf5//SY60I11_Measurement_26_08_2024_13_55_44_Default_Session.hdf5" {
DATASET "/Data/Frame_Data_Cube_0000_0000" {
   DATATYPE  H5T_IEEE_F32LE
   DATASPACE  SIMPLE { ( 256, 1, 1, 64 ) / ( 256, 1, 1, 64 ) }
   DATA {
   (0,0,0,0): 1856, 1849, 1864, 1862, 1860, 1864, 1866, 1856, 1860, 1858,
   (0,0,0,10): 1862, 1858, 1860, 1858, 1858, 1857, 1867, 1876, 1852, 1860,
   (0,0,0,20): 1864, 1860, 1869, 1858, 1854, 1866, 1864, 1857, 1862, 1860,
   (0,0,0,30): 1864, 1856, 1869, 1868, 1866, 1859, 1864, 1866, 1866, 1858,
   (0,0,0,40): 1858, 1866, 1864, 1866, 1854, 1858, 1860, 1862, 1869, 1864,
   (0,0,0,50): 1868, 1862, 1872, 1868, 1860, 1864, 1862, 1870, 1855, 1862,
   (0,0,0,60): 1865, 1862, 1860, 1868,
   (1,0,0,0): 1836, 1840, 1852, 1850, 1848, 1852, 1858, 1848, 1852, 1852,
   (1,0,0,10): 1850, 1850, 1850, 1850, 1854, 1850, 1854, 1862, 1844, 1852,
   (1,0,0,20): 1856, 1848, 1

In [39]:
!h5dump -g /Metadata {radar_meas_hdf5_file_path}

HDF5 "/home/jurnijasted/coding/sykno/MiRa_IFX_60GHz_2x4/sykno_radar_gui/sykno_radar_eval_project/radar_eval/measurement/hdf5//SY60I11_Measurement_26_08_2024_13_55_44_Default_Session.hdf5" {
GROUP "/Metadata" {
   GROUP "mira_bgt_reg_content" {
      ATTRIBUTE "mira_bgt_reg_content" {
         DATATYPE  H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_UTF8;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "reg 0x00 0x1c0e20
           reg 0x01 0x0a0210
           reg 0x02 0x00070c
           reg 0x03 0x000000
           reg 0x04 0xe967fd
           reg 0x05 0x0805b4
           reg 0x06 0x1503ff
           reg 0x07 0x000000
           reg 0x08 0x000000
           reg 0x0c 0x000000
           reg 0x10 0x003c71
           reg 0x13 0x000000
           reg 0x17 0x000000
           reg 0x1a 0x000000
           reg 0x1e 0x000000
           reg 0x21 0x000000
           reg 0x25 0x000000
 

In [40]:
!h5stat {radar_meas_hdf5_file_path}

Filename: /home/jurnijasted/coding/sykno/MiRa_IFX_60GHz_2x4/sykno_radar_gui/sykno_radar_eval_project/radar_eval/measurement/hdf5//SY60I11_Measurement_26_08_2024_13_55_44_Default_Session.hdf5
File information
	# of unique groups: 7
	# of unique datasets: 83
	# of unique named datatypes: 0
	# of unique links: 0
	# of unique other: 0
	Max. # of links to object: 1
	Max. # of objects in group: 82
File space information for file metadata (in bytes):
	Superblock: 96
	Superblock extension: 0
	User block: 0
	Object headers: (total/unused)
		Groups: 616/0
		Datasets(exclude compact data): 37008/2144
		Datatypes: 0/0
	Groups:
		B-tree/List: 11352
		Heap: 3656
	Attributes:
		B-tree/List: 0
		Heap: 0
	Chunked datasets:
		Index: 299792
	Datasets:
		Heap: 0
	Shared Messages:
		Header: 0
		B-tree/List: 0
		Heap: 0
	Free-space managers:
		Header: 0
		Amount of free space: 0
Small groups (with 0 to 9 links):
	# of groups with 0 link(s): 3
	# of groups with 1 link(s): 1
	# of groups with 2 link(s): 1
	# 

___
### __Radar Data Evaluation__ - ___Python Code___


#### ***Radar HDF5 Controller Usage***


In [41]:
import os
import numpy as np
import ipywidgets as widgets
from radar_eval.measurement.hdf5_controller import MIRA_HDF5_CTRL
from radar_eval.radar_system.radar_system_definition import MIRA_RADAR_PARAMETER
radar_meas_hdf5_path = './radar_eval/measurement/hdf5/'

# List all files in the folder
file_names = os.listdir(radar_meas_hdf5_path)

# Filter out non-file entries if needed
file_names = [f for f in file_names if os.path.isfile(os.path.join(radar_meas_hdf5_path, f)) and f != '.gitkeep']
sorted_file_names = sorted(file_names)

# Dropdown for file selection
file_dropdown = widgets.Dropdown(
    options=file_names,
    description=f'Select a File:',
)
print((f'Radar HDF5 Files in {radar_meas_hdf5_path}:'))
file_dropdown.layout.width = '650px'  # Adjust the width as needed
display(file_dropdown)



Radar HDF5 Files in ./radar_eval/measurement/hdf5/:


Dropdown(description='Select a File:', layout=Layout(width='650px'), options=('SY60I11_Measurement_26_08_2024_…

In [42]:
from pathlib import Path
radar_hdf5_controller = MIRA_HDF5_CTRL(Path(radar_meas_hdf5_path+str(file_dropdown.value)).resolve())
data = radar_hdf5_controller.read_dataset("/Data/Frame_Data_Cube_0000_0000")
print(data)

[[[[1.856e+03 1.849e+03 1.864e+03 ... 1.862e+03 1.860e+03 1.868e+03]]]


 [[[1.836e+03 1.840e+03 1.852e+03 ... 1.850e+03 1.852e+03 1.856e+03]]]


 [[[1.778e+03 1.771e+03 1.786e+03 ... 1.782e+03 1.780e+03 1.788e+03]]]


 ...


 [[[1.000e+00 1.000e+00 1.000e+00 ... 1.000e+00 1.000e+00 1.000e+00]]]


 [[[1.000e+00 1.000e+00 1.000e+00 ... 1.000e+00 1.000e+00 1.000e+00]]]


 [[[3.600e+01 3.500e+01 4.200e+01 ... 5.000e+01 5.000e+01 4.600e+01]]]]


In [43]:
radar_hdf5_controller.print_hdf5_structure()

- /
  - Data
    - Frame_Data_Cube_0000_0000 (Dataset)
      - @delta_time: 0.12029099464416504
      - @shape: (256, 1, 1, 64)
      - @timestamp: 1724673344.6665933
    - Frame_Data_Cube_0000_0001 (Dataset)
      - @delta_time: 0.0243990421295166
      - @shape: (256, 1, 1, 64)
      - @timestamp: 1724673344.6909924
    - Frame_Data_Cube_0000_0002 (Dataset)
      - @delta_time: 0.02693009376525879
      - @shape: (256, 1, 1, 64)
      - @timestamp: 1724673344.7179224
    - Frame_Data_Cube_0000_0003 (Dataset)
      - @delta_time: 0.027491092681884766
      - @shape: (256, 1, 1, 64)
      - @timestamp: 1724673344.7454135
    - Frame_Data_Cube_0000_0004 (Dataset)
      - @delta_time: 0.026865720748901367
      - @shape: (256, 1, 1, 64)
      - @timestamp: 1724673344.7722793
    - Frame_Data_Cube_0000_0005 (Dataset)
      - @delta_time: 0.026710987091064453
      - @shape: (256, 1, 1, 64)
      - @timestamp: 1724673344.7989902
    - Frame_Data_Cube_0000_0006 (Dataset)
      - @delta_time

In [44]:
stats = radar_hdf5_controller.get_dataset_statistics("/Data/Frame_Data_Cube_0000_0001")
print(stats)

{'mean': np.float32(1822.8093), 'std_dev': np.float32(1229.4701), 'min': np.float32(1.0), 'max': np.float32(4094.0)}


In [45]:
info = radar_hdf5_controller.get_dataset_info("/Data/Frame_Data_Cube_0000_0000")
print(info)

((256, 1, 1, 64), dtype('<f4'))


In [46]:
frame_data_cube = radar_hdf5_controller.get_dataset_slice("/Data/Frame_Data_Cube_0000_0000")

In [47]:
metadata = radar_hdf5_controller.read_metadata()
print(metadata)

{'mira_bgt_reg_content': {'mira_bgt_reg_content': 'reg 0x00 0x1c0e20\nreg 0x01 0x0a0210\nreg 0x02 0x00070c\nreg 0x03 0x000000\nreg 0x04 0xe967fd\nreg 0x05 0x0805b4\nreg 0x06 0x1503ff\nreg 0x07 0x000000\nreg 0x08 0x000000\nreg 0x0c 0x000000\nreg 0x10 0x003c71\nreg 0x13 0x000000\nreg 0x17 0x000000\nreg 0x1a 0x000000\nreg 0x1e 0x000000\nreg 0x21 0x000000\nreg 0x25 0x000000\nreg 0x28 0x000000\nreg 0x09 0x000000\nreg 0x0d 0x000000\nreg 0x11 0x13c610\nreg 0x14 0x000210\nreg 0x18 0x000210\nreg 0x1b 0x000210\nreg 0x1f 0x000210\nreg 0x22 0x000210\nreg 0x26 0x000210\nreg 0x29 0x000210\nreg 0x0a 0x000000\nreg 0x0e 0x000000\nreg 0x12 0x808421\nreg 0x15 0x808421\nreg 0x19 0x808421\nreg 0x1c 0x808421\nreg 0x20 0x808421\nreg 0x23 0x808421\nreg 0x27 0x808421\nreg 0x2a 0x808421\nreg 0x0b 0x0009e0\nreg 0x0f 0x000960\nreg 0x16 0x000090\nreg 0x1d 0x000080\nreg 0x24 0x000080\nreg 0x2b 0x000080\nreg 0x2c 0x11be0e\nreg 0x2d 0x3cd40a\nreg 0x2e 0x03f000\nreg 0x2f 0xbf3e1e\nreg 0x30 0xa9ffff\nreg 0x38 0xa9ffff\

In [48]:
radar_param: MIRA_RADAR_PARAMETER = radar_hdf5_controller.unpickle_metadata()
print(radar_param)

In [49]:
radar_data_cube = np.array(radar_hdf5_controller.load_radar_data_cube(), dtype=np.float32)
print(radar_data_cube.shape, radar_data_cube.dtype)

(82, 256, 1, 1, 64) float32


---
#### ***Inspect radar dataset***

1. **Load python packages and radar HDF5 measurement file**


2. **Open Radar HDF5 measurement file, load meta data and build radar data cube**

3. **Radar HDF5 measurement - data profiling**

    __Inspect Radar Radar System Parameters__
    - __radar_param__: meta-class contains __All__ other sub-classes
        - __sys__: sub-class contains __Radar__ specific values
        - __dsp__: sub-class contains __DSP__ parameters
        - __mon__: sub-class to __Monitor__ frame count, duration time, etc.
        - __gui__: sub-class contains __GUI__ relevant parameters
        - __meas__: sub-class contains __Measurement__ relevant parameters
        - __remt__: sub-class contains __Remote Control__ relevant parameters
        - __rply__: sub-class contains __Replay Control__ relevant parameters 

In [50]:
print(f"{radar_param.__dict__=}")
print(f"{radar_param.dsp.__dict__=}")
print(f"{radar_param.gui.__dict__=}")
print(f"{radar_param.mon.__dict__=}")
print(f"{radar_param.sys.__dict__=}")
print(f"{radar_param.meas.__dict__=}")
print(f"{radar_param.remt.__dict__=}")
print(f"{radar_param.rply.__dict__=}")

radar_param.__dict__={'gui': <radar_eval.radar_system.radar_system_definition.MIRA_RADAR_GUI_PARAMETER object at 0x73e2dbe6ef80>, 'dsp': <radar_eval.radar_system.radar_system_definition.MIRA_RADAR_DSP_PARAMETER object at 0x73e2dbe6ef20>, 'sens': <radar_eval.radar_system.radar_system_definition.MIRA_RADAR_SENS_PARAMETER object at 0x73e2dbe6fc40>, 'sys': <radar_eval.radar_system.radar_system_definition.MIRA_RADAR_SYS_PARAMETER object at 0x73e2dbe6d1b0>, 'mon': <radar_eval.radar_system.radar_system_definition.MIRA_RADAR_MON_PARAMETER object at 0x73e2dbe6fa60>, 'meas': <radar_eval.radar_system.radar_system_definition.MIRA_RADAR_MEAS_PARAMETER object at 0x73e2dbe6ee90>, 'rply': <radar_eval.radar_system.radar_system_definition.MIRA_RADAR_RPLY_PARAMETER object at 0x73e2dbe6ed70>, 'remt': <radar_eval.radar_system.radar_system_definition.MIRA_RADAR_REMT_PARAMETER object at 0x73e2dbe6fa90>}
radar_param.dsp.__dict__={'axis_max_value': np.uint32(0), 'padding_len': 512, 'window_func': 'hanning', 'a

3. **Radar HDF5 measurement - data profiling**

    1. __Check Radar System Parameters__
    - __radar_param__: meta-class contains __All__ other sub-classes

In [51]:
print(f"{radar_data_cube.shape=}")
print(f"{frame_data_cube.shape=}\n" + \
      f"{radar_hdf5_controller.delta_time=}\n" + \
      f"{radar_hdf5_controller.shape=}\n" + \
      f"{radar_hdf5_controller.timestamp=}")

print(f"{frame_data_cube[:1,:,:,0]}")


radar_data_cube.shape=(82, 256, 1, 1, 64)
frame_data_cube.shape=(256, 1, 1, 64)
radar_hdf5_controller.delta_time=None
radar_hdf5_controller.shape=None
radar_hdf5_controller.timestamp=None
[[[1856.]]]
